### PR TITLE
[WFCORE-1167] Update jboss-invocation to 1.5.0.Beta1

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.jboss.org/browse/WFCORE-1167

### CODE REVIEW

**Comment by darranl** [comment]
Do we also need an incubator fork of JBoss Invocation or are changes being merged quickly enough the dependency update is sufficient?

**Comment by dmlloyd** [comment]
I've released 1.5.0.Beta1 of jboss-invocation which we can use.

**Comment by darranl** [comment]
Thanks @dmlloyd, @fjuma are you Ok to update this to the tagged Beta?

**Comment by fjuma** [comment]
Thanks, @dmlloyd. I've updated this to the tagged Beta.

**Pull request merged**
