### PR TITLE
[WFCORE-2565]: Incorrect permission class-name should throw exception at runtime

### PR DESCRIPTION
**Pull request by ehsavoie**
Logging a WARNING when the class of a permission can't be loaded.

Jira: https://issues.jboss.org/browse/WFCORE-2565
JBEAP: https://issues.jboss.org/browse/JBEAP-9726

### CODE REVIEW

**Comment by darranl** [comment]
I think this is going to need some further thought, I have just checked and we do support 'UNLESS' within the mappings - this does mean a missing permission could inadvertently allow access that should not be granted.

**Comment by ehsavoie** [comment]
Since we have our 'own' SimplePermissionWriteAttributeHandler we can put more logic in there.

**Comment by darranl** [comment]
I think realistically we are going to have to keep the services failing start up if the permission is not found.

I am not really keen on adding a runtime handler just for the purpose of validating the permissions, especially on a resource that does not support runtime updates.  

Maybe we would be better supporting runtime updates on the resource but most Elytron resources don't support this at the moment, it still doesn't cover the scenario of a slave connecting to the domain after the configuration has been updated so at best it would only ever be a partial validation.

**Comment by bstansberry** [comment]
Should this be closed?

**Pull request closed without merging**
