### PR TITLE
[WFCORE-2415] credential-reference must have defined combinations of constraints

### PR DESCRIPTION
**Pull request by ivassile**
wildfly-core: https://issues.jboss.org/browse/WFCORE-2415
JBEAP: https://issues.jboss.org/browse/JBEAP-9308

### CODE REVIEW

**Comment by darranl** [comment]
For this one I think we need to wait for the PR for https://issues.jboss.org/browse/WFCORE-2317 to be resolved first.

**Comment by darranl** [comment]
This one does currently have a conflict as well but I think we still need to wait for the related fix to be in first before we pick this one up again.

**Review by kabir — APPROVED** [review]

**Review by pskopek — APPROVED** [review]

**Comment by darranl** [comment]
This PR needs to be held for now as it will be dependent on the changes being implemented for this issue https://issues.jboss.org/browse/WFCORE-2317

**Comment by msve** [comment]
Downstream jira has dev ack- currently. If WFCORE-2317 gets resolved and this PR will be merged, please don't forget to change it to dev ack+.

**Comment by thaarok** [comment]
Looks like this brokes test of wildfly:
```
testTransformerElytronEnabledEAP64(org.jboss.as.connector.subsystems.datasources.DatasourcesSubsystemTestCase)  Time elapsed: 0.451 sec  <<< FAILURE!
java.lang.AssertionError: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-6" => "WFLYCTL0105: recovery-credential-reference.store is invalid in combination with recovery-credential-reference.clear-text"}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.jboss.as.model.test.ModelTestUtils.checkOutcome(ModelTestUtils.java:135)
	at org.jboss.as.model.test.ModelTestUtils.checkFailedTransformedBootOperations(ModelTestUtils.java:594)
	at org.jboss.as.connector.subsystems.datasources.DatasourcesSubsystemTestCase.testTransformerElytronEnabled(DatasourcesSubsystemTestCase.java:219)
	at org.jboss.as.connector.subsystems.datasources.DatasourcesSubsystemTestCase.testTransformerElytronEnabledEAP64(DatasourcesSubsystemTestCase.java:146)
```

**Pull request merged**
