### PR TITLE
[WFCORE-2559] - minor change to utilize upstream ELY issue

### PR DESCRIPTION
**Pull request by baranowb**
https://issues.jboss.org/browse/WFCORE-2559

Requires: https://issues.jboss.org/browse/ELY-1062
Enabler: https://issues.jboss.org/browse/JBEAP-9684

### CODE REVIEW

**Comment by darranl** [comment]
FYI for new PRs can you please include a link to the JBEAP issue in the PR description?  We are now at the point of only accepting approved changes so the release coordinator is verifying all PRs before they are merged.

**Comment by baranowb** [comment]
Sure.

**Review by kabir — APPROVED** [review]
Approving paperwork is in order

**Comment by baranowb** [comment]
No longer valid. ELY component cant have names.

**Pull request closed without merging**
