### PR TITLE
WFCORE-2500 Elytron: setting reload-required on http-server-mechanism…

### PR DESCRIPTION
**Pull request by TomasHofman**
…-factory of http-authentication-factory

https://issues.jboss.org/browse/WFCORE-2500
https://issues.jboss.org/browse/JBEAP-9373

This reverts the original PR https://github.com/wildfly-security-incubator/wildfly-core/pull/76, where I set the flags on a wrong attribute, and makes the change on a correct attribute.

### CODE REVIEW

**Comment by bstansberry** [comment]
@TomasHofman shall I assign WFCORE-2631 / JBEAP-10168 to you? Your TrivialResourceDefinition change is definitely aimed at those. I think all that would be needed would be an audit of the TrivialResourceDefinition uses to make sure all the top level attributes have the correct flags. Which you may have already done. :)

I planned to fix WFCORE-2631 via a change in RestartParentWriteAttributeHandler (see WFCORE-2688) but since this addresses the key issue in elytron and there are plenty of other things to do I'm happy to leave it for now. The WFCORE-2688 change would be more work.

**Comment by TomasHofman** [comment]
@bstansberry sure, I will look into them.

**Review by kabir — APPROVED** [review]
Approving paperwork

**Comment by darranl** [comment]
@bstansberry as this is really management API use are you able to give this one a quick review?

**Review by bstansberry — APPROVED** [review]
@darranl It's good. For a different JIRA there's some discussion of doing more (i.e. implementing restartParentService in some handlers) and I'm considering doing much the same as what he does here in TrivialResourceDefinition in RestartParentWriteAttributeHandler itself, but what is done here is correct, doesn't interfere with what I would do, and helps make what I thought about doing into something that could be deferred to Core 4. So +1 from me.

**Pull request merged**
